### ISSUE TITLE
Add support for Claude Code Pro Plan

### ISSUE THREAD

**Issue by seri114** [grll/claude-code-base-action#1]
## Summary

Add support for Claude Code Pro Plan to allow users to leverage enhanced capabilities and higher usage limits when running Claude Code in GitHub Actions.

## Background

Claude Code Pro Plan offers additional benefits including:
- Higher usage limits
- Enhanced performance
- Priority access to new features
- Extended context windows

Currently, the GitHub Action only supports standard Claude Code usage and doesn't provide a way to specify Pro Plan credentials or configuration.

## Proposed Solution

Add support for Claude Code Pro Plan by:

1. **New Input Parameter**: Add a `pro_plan` boolean input to `action.yml` to enable Pro Plan mode
2. **Authentication Enhancement**: Ensure Pro Plan API keys are properly handled and distinguished from standard API keys
3. **Configuration Updates**: Update the Claude Code execution to use Pro Plan endpoints/configuration when enabled
4. **Documentation**: Update README and action documentation to explain Pro Plan usage

### Action Input
```yaml
pro_plan:
  description: 'Enable Claude Code Pro Plan features'
  required: false
  default: 'false'
```

### Usage Example
```yaml
- uses: anthropics/claude-code-base-action@v1
  with:
    anthropic_api_key: ${{ secrets.ANTHROPIC_PRO_API_KEY }}
    pro_plan: true
    prompt: "Analyze this codebase and suggest improvements"
```

## Benefits

- Enables users with Pro Plan subscriptions to fully utilize their enhanced capabilities
- Provides better performance and higher limits for enterprise workflows
- Future-proofs the action for upcoming Pro Plan features

## Acceptance Criteria

- [ ] Pro Plan mode can be enabled via input parameter
- [ ] Pro Plan API keys are properly authenticated
- [ ] Enhanced limits and features are available when Pro Plan is enabled
- [ ] Documentation is updated with Pro Plan usage examples
- [ ] Tests cover both standard and Pro Plan modes

## Priority

This enhancement would benefit enterprise users and teams with Pro Plan subscriptions who want to integrate Claude Code into their CI/CD workflows with full capabilities.
